Initial code sample for Roles API.
EENCloud/VMS-Developer-Portal pull request #29
Opened 2024-12-30 12:15 UTC by mvleest-code

Initial code sample for Roles API.

2025-01-09 11:49 UTC, mvleest-code commented
Added een_client.py

2025-01-09 19:04 UTC, DMalone87 requested changes
Login flow isn't working properly as is. It seems like the Redirect URL logic is incomplete.

2025-01-09 19:04 UTC, DMalone87 commented on EEN Roles/app/routes.py
> +    if code:
This code pickup is in the wrong place. The user gets redirected back to the index page (`/`), not `/login`.

2025-01-10 11:51 UTC, mvleest-code commented on EEN Roles/app/routes.py
> +    if code:
Thanks for the catch on that last one. and added the REDIRECT_URI

2025-01-13 19:07 UTC, DMalone87 approved these changes

2025-01-14 15:22 UTC, merged